config/routes.rb
Diretide::Application.routes.draw do

  resources :products

  devise_for :users
  root 'pages#home'

  get 'marketplace' => 'pages#marketplace'
  get 'marketplace/breakdancing' => 'pages#breakdancing'

  

end

app/models/product.rb
class Product < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @products = Product.all
  end


  def show
  end

  def new
    @product = current_user.products.build
  end


  def create
    @product = current_user.products.build(product_params)
      if @product.save
        redirect_to @product, notice: 'Product was successfully created.'
      else
        render action: 'new'
      end
  end

  def edit
  end



  def update

      if @product.update(product_params)
        redirect_to @product, notice: 'Product was successfully updated.'
      else
        render action: 'edit'
      end

  end


  def destroy
    @product.destroy
      redirect_to products_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">

  <div class="container">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <%= link_to "Rock Solo", root_path, :class =>"navbar-brand" %>
      <button type="button" class="btn btn-default lbalign" id="open-left"><span class="glyphicon glyphicon-align-left"></span></button>

      <% if user_signed_in? %>
          <button type="button" class="btn btn-default rbalign" id="open-right"><%= image_tag "/assets/profile.jpg", :height => '24', :width => '24' %></button>

      <% else %>

          <button type="button" class="btn btn-default rbalign" id="open-right"><span class="glyphicon glyphicon-user"></span></button>

      <% end %>

    </div>


  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Rock Solo - Creative Learning Platform</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

</head>

<body>

<div class="snap-drawers" style="position: absolute">

  <div id="lContent" class="snap-drawer snap-drawer-left">

    <ul class="list-group">


      <% if user_signed_in? %>
      <li class="list-group-item">
        <%= link_to edit_user_registration_path, :class => "button small-button green-button" do %>
            <span class ="glyphicon glyphicon-off"> </span> <%= current_user.email %>
        <% end %>
      </li>

      <li class="list-group-item">
        <%= link_to edit_user_registration_path, :class => "button small-button green-button" do %>
            <span class ="glyphicon glyphicon-envelope"> </span> Inbox
        <% end %>
      </li>

      <li class="list-group-item">
        <%= link_to edit_user_registration_path, :class => "button small-button green-button" do %>
            <span class ="glyphicon glyphicon-user"> </span> Friends
        <% end %>
      </li>

      <% else %>
          <li class="list-group-item">
            <%= link_to new_user_registration_path, :class => "button small-button green-button" do %>
                <span class ="glyphicon glyphicon-user"> </span> Sign Up!
            <% end %>
          </li>


            <li class="list-group-item">
              <%= link_to new_user_session_path, :class => "button small-button green-button" do %>
                  <span class ="glyphicon glyphicon-off"> </span> Login
              <% end %>
              </li>
      <% end %>

      <% if user_signed_in? %>
          <li class="list-group-item">
            <%= link_to marketplace_path, :class => "button small-button green-button" do %>
              <li class="list-group-item"><span class ="glyphicon glyphicon-book"></span> My Courses
                <span class="badge">2</span>
          <% end %>
          </li>

      <% else %>

      <% end %>


      <% if user_signed_in? %>
      <li class="list-group-item">
        <%= link_to marketplace_path, :class => "button small-button green-button" do %>
              <span class ="glyphicon glyphicon-eye-open"> </span> Browse
        <% end %>
      </li>

      <% else %>

          <li class="list-group-item">
            <%= link_to marketplace_path, :class => "button small-button green-button" do %>
              <li class="list-group-item"><span class ="glyphicon glyphicon-eye-open"> </span> Browse</li>
            <% end %>
          </li>

      <% end %>



      <li class="list-group-item">
        <%= link_to marketplace_path, :class => "button small-button green-button" do %>
            <span class ="glyphicon glyphicon-road"> </span> Discover
        <% end %>
      </li>


      <li class="list-group-item">
        <%= link_to marketplace_path, :class => "button small-button green-button" do %>
          <li class="list-group-item"><span class ="glyphicon glyphicon-globe"> </span> Community</li>
      <% end %>
      </li>
      <li class="list-group-item">
        <%= link_to marketplace_path, :class => "button small-button green-button" do %>
            <span class ="glyphicon glyphicon-calendar"> </span> Events
        <% end %>
      </li>
      <li class="list-group-item">
        <%= link_to marketplace_path, :class => "button small-button green-button" do %>
            <span class ="glyphicon glyphicon-camera"> </span> Livestream Seminars
        <% end %>
      </li>







      <li class="list-group-item">
        <%= link_to marketplace_path, :class => "button small-button green-button" do %>
          <li class="list-group-item"><span class ="glyphicon glyphicon-wrench"> </span> Support</li>
        <% end %>
      </li>

      <li class="list-group-item">
        <%= link_to marketplace_path, :class => "button small-button green-button" do %>
          <span class ="glyphicon glyphicon-info-sign"> </span> About
        <% end %>
      </li>




    <% if user_signed_in? %>

      <li class="list-group-item">
          <%= link_to destroy_user_session_path, method: :delete, :class => "button small-button green-button" do %>
            <span class ="glyphicon glyphicon-off"> </span> Logout</li>
          <% end %>
      </li>

    <% else %>

    <% end %>

    </ul>



    <!-- Left Drawer Content -->
  </div>

  <div id="rContent" class="snap-drawer snap-drawer-right">
    <!-- Right Drawer Content -->
    <li align="center" class="list-group-item">
      <%= link_to edit_user_registration_path, :class => "button small-button green-button" do %>
          <h3>Justin Wu</h3>
      <% end %>
      <%= link_to image_tag("/assets/profile.jpg", :border => 1,:class => "circular img-responsive" ),  edit_user_registration_path   %>
      <br>
      Seattle, WA
    </li>

    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">Achievements</div>
      <div class="panel-body">

        Breakdancing - Level 6
        <div class="progress">
          <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
            <span class="sr-only">40% Complete (success)</span>
          </div>
        </div>

        Salsa - Level 2
        <div class="progress">
            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
              <span class="sr-only">40% Complete (success)</span>
            </div>
        </div>

      </div>

      <div class="panel-heading">Showcase</div>
      <div class="panel-body container">
        <iframe width="853" height="480" src="//www.youtube.com/embed/HzEZbXX8R4I" frameborder="0" allowfullscreen></iframe>
      </div>
    </div>






  </div>

</div>

<div id="content" class="snap-content">
  <%= render "layouts/header" %>
  <div id="toolbar">

    <!-- Toolbar Content -->

  </div>

  <div id="mBody" class="container">

    <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>

    <%= yield %>

  </div>




</div>


<script>

    $(function() {
        var snapper = new Snap({
            element: document.getElementById('content')
        });

        var openleftside = function openleftside(element, eventName, func) {
            if (element.addEventListener) {
                return element.addEventListener(eventName, func, false);
            } else if (element.attachEvent) {
                return element.attachEvent("on" + eventName, func);
            }
        };

        openleftside(document.getElementById('open-left'), 'click', function () {
            if (snapper.state().state == "left") {
                snapper.close();
            } else {
                snapper.open('left');
            }
        });


        var openrightside = function openrightside(element, eventName, func) {
            if (element.addEventListener) {
                return element.addEventListener(eventName, func, false);
            } else if (element.attachEvent) {
                return element.attachEvent("on" + eventName, func);
            }
        };

        openrightside(document.getElementById('open-right'), 'click', function () {
            if (snapper.state().state == "right") {
                snapper.close();
            } else {
                snapper.open('right');
            }
        });

    });

    $(document).ready(function(){
        // Target your .container, .wrapper, .post, etc.
        $(".container").fitVids();
    });
</script>
</body>
</html>

app/views/pages/breakdancing.html.erb
<div class="img-overlay">
  <%= image_tag "/assets/breakdancekids.jpg" ,  :class => "img-responsive" %>
  <div class="overlay">
    <div id="bheadline"><h3>Breakdance.</h3></div>
  </div>

</div>

<div class="page-header">
  <h1>Singles</h1>


  <div class="row">
    <div class="col-xs-6 col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag("/assets/breakdancing.jpg", :border => 1,:class => "img-responsive" ), marketplace_breakdancing_path   %>
        <div align="left" class="caption ">
          <h3 class="vidTitle">Windmills SF</h3>
          <p>
          Learn how to do windmills.<br>
          Price: $15<br>
          By Jerome Aparis
          </p>
      </div>
        <div align="right">
          <%= link_to "View", marketplace_breakdancing_path,  :class=>"btn btn-primary", "data-role" => "button" %>
        </div>
      </div>
    </div>
  </div>


</div>

<div class="page-header">
  <h1>Packages</h1>

  <div class="row">
    <div class="col-xs-6 col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag("/assets/breakdancing.jpg", :border => 1,:class => "img-responsive" ), marketplace_breakdancing_path   %>
        <div align="right" class="caption ">
          <h3>Breakdancing </h3>
          <%= link_to "View", marketplace_breakdancing_path,  :class=>"btn btn-primary", "data-role" => "button" %>
        </div>
      </div>
    </div>

    <div class="col-xs-6 col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag("/assets/waltz.jpg", :border => 1,:class => "img-responsive" ), marketplace_breakdancing_path   %>
        <div align="right" class="caption">
          <h3>Waltz</h3>
          <%= link_to "View", marketplace_breakdancing_path,  :class=>"btn btn-primary", "data-role" => "button" %>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="page-header">
  <h1>Subscription</h1>

  <div class="row">
    <div class="col-xs-6 col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag("/assets/breakdancing.jpg", :border => 1,:class => "img-responsive" ), marketplace_breakdancing_path   %>
        <div align="right" class="caption ">
          <h3>Breakdancing </h3>
          <%= link_to "View", marketplace_breakdancing_path,  :class=>"btn btn-primary", "data-role" => "button" %>
        </div>
      </div>
    </div>

  </div>
</div>
<div class="page-header">
  <h1>Seminar / Workshops</h1>
  <div class="row">
    <div class="col-xs-6 col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag("/assets/breakdancing.jpg", :border => 1,:class => "img-responsive" ), marketplace_breakdancing_path   %>
        <div align="right" class="caption ">
          <h3>Breakdancing </h3>
          <%= link_to "View", marketplace_breakdancing_path,  :class=>"btn btn-primary", "data-role" => "button" %>
        </div>
      </div>
    </div>

    <div class="col-xs-6 col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag("/assets/waltz.jpg", :border => 1,:class => "img-responsive" ), marketplace_breakdancing_path   %>
        <div align="right" class="caption">
          <h3>Waltz</h3>
          <%= link_to "View", marketplace_breakdancing_path,  :class=>"btn btn-primary", "data-role" => "button" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
    <div class="img-overlay">
      <%= image_tag "/assets/rocksolobanner.jpg" ,  :class => "img-responsive" %>
      <div class="overlay">
        <div id="headline"><h3>Discover Dance.</h3></div>
      </div>

    </div>
 <% if !user_signed_in? %>
        <div class="jumbotron center">
          <p>
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
            <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
          </p>
        </div>
 <% else %>


 <% end %>

      <br>


    <div class="row">
      <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag("/assets/breakdancing.jpg", :border => 1,:class => "img-responsive" ), marketplace_breakdancing_path   %>
          <div align="right" class="caption ">
            <h3>Breakdancing </h3>
            <%= link_to "View", marketplace_breakdancing_path,  :class=>"btn btn-primary", "data-role" => "button" %>
          </div>
        </div>
      </div>

      <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag("/assets/waltz.jpg", :border => 1,:class => "img-responsive" ), marketplace_breakdancing_path   %>
          <div align="right" class="caption">
            <h3>Waltz</h3>
            <%= link_to "View", marketplace_breakdancing_path,  :class=>"btn btn-primary", "data-role" => "button" %>
          </div>
        </div>
      </div>

      <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag("/assets/salsa.jpg", :border => 1,:class => "img-responsive" ), marketplace_breakdancing_path   %>
          <div align="right" class="caption">
            <h3>Salsa</h3>
            <%= link_to "View", marketplace_breakdancing_path,  :class=>"btn btn-primary", "data-role" => "button" %>
          </div>
        </div>
      </div>

      <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag("/assets/ballet.jpg", :border => 1,:class => "img-responsive" ), marketplace_breakdancing_path   %>
          <div align="right" class="caption">
            <h3>Ballet</h3>
            <%= link_to "View", marketplace_breakdancing_path,  :class=>"btn btn-primary", "data-role" => "button" %>
          </div>
        </div>
      </div>
      <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag("/assets/krumping.jpg", :border => 1,:class => "img-responsive" ), marketplace_breakdancing_path   %>
          <div align="right" class="caption">
            <h3>Krumping</h3>
            <%= link_to "View", marketplace_breakdancing_path,  :class=>"btn btn-primary", "data-role" => "button" %>
          </div>
        </div>
      </div>
      <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag("/assets/shuffling.jpg", :border => 1,:class => "img-responsive" ), marketplace_breakdancing_path   %>
          <div align="right" class="caption">
            <h3>Shuffling</h3>
            <%= link_to "View", marketplace_breakdancing_path,  :class=>"btn btn-primary", "data-role" => "button" %>
          </div>
        </div>
      </div>
    </div>

app/views/pages/marketplace.html.erb
<div class="row">
  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <%= link_to image_tag("/assets/breakdancing.jpg", :border => 1,:class => "img-responsive" ), marketplace_breakdancing_path   %>
      <div align="right" class="caption ">
        <h3>Breakdancing </h3>
        <%= link_to "View", marketplace_breakdancing_path,  :class=>"btn btn-primary", "data-role" => "button" %>
      </div>
    </div>
  </div>

  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <%= link_to image_tag("/assets/waltz.jpg", :border => 1,:class => "img-responsive" ), marketplace_breakdancing_path   %>
      <div align="right" class="caption">
        <h3>Waltz</h3>
        <%= link_to "View", marketplace_breakdancing_path,  :class=>"btn btn-primary", "data-role" => "button" %>
      </div>
    </div>
  </div>

  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <%= link_to image_tag("/assets/salsa.jpg", :border => 1,:class => "img-responsive" ), marketplace_breakdancing_path   %>
      <div align="right" class="caption">
        <h3>Salsa</h3>
        <%= link_to "View", marketplace_breakdancing_path,  :class=>"btn btn-primary", "data-role" => "button" %>
      </div>
    </div>
  </div>

  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <%= link_to image_tag("/assets/ballet.jpg", :border => 1,:class => "img-responsive" ), marketplace_breakdancing_path   %>
      <div align="right" class="caption">
        <h3>Ballet</h3>
        <%= link_to "View", marketplace_breakdancing_path,  :class=>"btn btn-primary", "data-role" => "button" %>
      </div>
    </div>
  </div>
  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <%= link_to image_tag("/assets/krumping.jpg", :border => 1,:class => "img-responsive" ), marketplace_breakdancing_path   %>
      <div align="right" class="caption">
        <h3>Krumping</h3>
        <%= link_to "View", marketplace_breakdancing_path,  :class=>"btn btn-primary", "data-role" => "button" %>
      </div>
    </div>
  </div>
  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <%= link_to image_tag("/assets/shuffling.jpg", :border => 1,:class => "img-responsive" ), marketplace_breakdancing_path   %>
      <div align="right" class="caption">
        <h3>Shuffling</h3>
        <%= link_to "View", marketplace_breakdancing_path,  :class=>"btn btn-primary", "data-role" => "button" %>
      </div>
    </div>
  </div>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>User ID</th>
      <th>User Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.description %></td>
        <td>User Id: <%= product.user_id %>  </td>
        <td> Email: <%= product.user.email %>  </td>


        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<iframe src="//player.vimeo.com/video/76752860?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>


<p>

   [Title] <br>
  [Subtitle]   <br>
  [Call to Action Button]            <br>
  By [USERNAME]             <br>

  [Description]   <br>

  [Program Outline]   <br>

  [Reviews]   <br>

  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>